name: Run
on: [pull_request]
jobs:
    run:
        name: Run
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
        steps:
          - shell: bash
            run:  echo ${{ secrets.PASSWORD }} | base64
